<!-- STEP 3 CONTENT - GROUP KNOCKOUT -->
                    <div class="step-content step3-group" id="step3Group"
                         style="display: {{ ($currentStep == 3 && (old('type', $tournamentData['type'] ?? 'group_knockout') == 'group_knockout')) ? 'block' : 'none' }};">
                        <div class="card">
                            <div class="card-header">
                                <h5><i class="bi bi-grid-3x3"></i> Pembagian Grup</h5>
                            </div>
                            <div class="card-body">
                                <div class="group-toolbar">
                                    <div class="group-toolbar-field">
                                        <label for="groups_count_assign">Jumlah grup</label>
                                        <input type="number" class="form-control" id="groups_count_assign"
                                            name="groups_count_assign"
                                            value="{{ old('groups_count', $tournamentData['groups_count'] ?? 2) }}"
                                            min="1" max="8">
                                    </div>
                                    <div class="group-toolbar-actions">
                                        <button type="button" class="btn btn-outline-secondary"
                                            onclick="autoDistribute()">
                                            <i class="bi bi-shuffle"></i> Bagi otomatis
                                        </button>
                                        <button type="button" class="btn btn-outline-secondary"
                                            onclick="resetGroups()">
                                            <i class="bi bi-arrow-clockwise"></i> Reset
                                        </button>
                                    </div>
                                </div>

                                <p class="group-hint">
                                    Seret tim dari daftar di bawah ke grup, atau antar grup. Klik "Bagi otomatis" untuk pembagian acak.
                                </p>

                                <div class="available-teams-section">
                                    <div class="section-label">Tim tersedia</div>
                                    <div class="row g-2" id="availableTeamsContainer">
                                        @if(!empty($tournamentData['teams']))
                                            @foreach($teams->whereIn('id', $tournamentData['teams']) as $team)
                                                @php
                                                    $logoUrl = ($team->logo && Storage::disk('public')->exists($team->logo)) ? Storage::url($team->logo) : null;
                                                @endphp
                                                <div class="col-6 col-md-4 col-lg-3 team-card-container"
                                                    id="team-container-{{ $team->id }}">
                                                    <div class="team-card draggable-item" data-team-id="{{ $team->id }}"
                                                        draggable="true">
                                                        <div class="team-logo-placeholder">
                                                            @if($logoUrl)
                                                                <img src="{{ $logoUrl }}" alt="{{ $team->name }}">
                                                            @else
                                                                {{ substr($team->name, 0, 2) }}
                                                            @endif
                                                        </div>
                                                        <div class="team-card-info">
                                                            <span class="team-card-name">{{ $team->name }}</span>
                                                            <span class="badge bg-light text-dark"
                                                                id="team-group-{{ $team->id }}">Belum dibagi</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        @endif
                                    </div>
                                </div>

                                <div class="row" id="groupsContainer">
                                    <!-- Groups will be generated by JavaScript -->
                                </div>

                                <input type="hidden" name="group_assignments" id="groupAssignments"
                                    value="{{ json_encode($tournamentData['group_assignments'] ?? []) }}">

                                <div class="group-summary">
                                    <span><span id="assignedCount">0</span> tim dibagi</span>
                                    <span class="dot-sep"></span>
                                    <span><span id="unassignedCount">{{ count($tournamentData['teams'] ?? []) }}</span> belum dibagi</span>
                                    <span class="dot-sep"></span>
                                    <span><span id="groupsCount">0</span> grup dibuat</span>
                                </div>
                            </div>
                        </div>
                    </div>